project:
  type: website
  output-dir: docs

website:
  title: "PlotOnePiece"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sciRplot.qmd
      - href: CNSplot.qmd
      - href: sciRcolor.qmd
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: left
    link-external-newwindow: true
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 100px
      gutter-width: 1.5rem

execute:
  freeze: auto

