project:
  type: website
  output-dir: docs

website:
  title: "PlotOnePiece"
  page-navigation: true
  site-url: https://zhengtiger.github.io/PlotOnePiece/
  repo-url: https://github.com/ZhengTiger/PlotOnePiece
  repo-actions:
    - source
    - issue
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sciRplot.qmd
      - href: sciRcolor.qmd
      - href: CNSplot.qmd
      - href: CNScolor.qmd
    right:
      - icon: github
        href: https://github.com/ZhengTiger/PlotOnePiece
  page-footer:
    center: "Copyright @ 2026 TigerZ生信宝库 All rights reserved."
      

format:
  html:
    theme:
      light: Flatly
      dark: Darkly
    css: styles.css
    toc: true
    toc-location: left
    link-external-newwindow: true
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 100px
      gutter-width: 1.5rem

execute:
  freeze: auto

lang: zh

